services:
  firewall_range:
    build: .
    container_name: linux_range_firewall
    # Keep the environment running persistently in the background
    command: /bin/bash -c "sleep infinity"
    # CRITICAL: Grants the container root capability access to host kernel and device mapping
    privileged: true