version: "3.9"

services:
  filesystem-lab:
    build: .
    image: linux-handbook-lab
    container_name: filesystem-lab

    tty: true
    stdin_open: true

    command: >
      bash -c "
      /opt/linux-handbook/lab/init.sh &&
      tail -f /dev/null
      "